check language and show localization messages
victoriadrake/git-rundown pull request #1
Opened 2020-03-03 16:44 UTC by victorhck

the original script didn't work for me, because git show messages in spanish.
This script, check $LANG variable and show different messages (now only english and spanish)
I haven't tested in English, can you please check if everything is ok in your system?
Greetings!!

2020-03-04 14:09 UTC, victoriadrake requested changes
Hello! Thank you for this translation, I love this idea!

I have some errors now in the English version output:

```sh
/home/v/src/ghub/git-rundown
master Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
./git-rundown/multilang.sh: line 66: [: -ne: unary operator expected
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
./git-rundown/multilang.sh: line 73: [: -ne: unary operator expected
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
./git-rundown/multilang.sh: line 80: [: -ne: unary operator expected
```

I think it is because the new variables need to be double quoted. Please see the review comment.

2020-03-04 14:09 UTC, victoriadrake commented on git-rundown.sh
> +		if [ $(git status | grep $check_modif -c) -ne 0 ]
Each variable needs double quotes throughout the script:

```suggestion
		if [ $(git status | grep "$check_modif" -c) -ne 0 ]
```
```

2020-03-04 15:46 UTC, victorhck commented
it's strange that works for Spanish and not in English... don't know why.
A new PR to test if everything now runs ok.

2020-03-05 02:52 UTC, victoriadrake commented
I realized the issue...

```sh
$ echo $LANG
en_US.UTF-8
```

Quick fix! If there is enough interest, the script may want to handle other locales as well.

2020-03-05 02:52 UTC, merged

2020-03-05 02:53 UTC, victoriadrake commented
Thank you @victorhck!

2020-03-05 07:04 UTC, victorhck commented
> 
> 
> Thank you @victorhck!

Thanks to you!! Was a pleasure to learn, hack a bit and contribute in your code! :)
Greatings!
PS: Maybe I'll blog about the script...

2020-03-05 15:46 UTC, victoriadrake commented
Please do! :+1: I'd love if you dropped a link here too!

2020-03-05 15:58 UTC, victorhck commented
> Please do! +1 I'd love if you dropped a link here too!

here you have: 
https://victorhckinthefreeworld.com/2020/03/05/comprueba-el-estado-de-multiples-repositorios-de-git-con-este-script/

even a asciinema demo:
https://asciinema.org/a/307752

:)

2020-03-05 16:23 UTC, victoriadrake commented
Very cool! ¡Muchas gracias por compartir!